# File containing the input data. The columns are:
# * 'id': name of the object.
# * 'redshift': redshift of the object. If 0, the distance is assumed to
# be 10 pc. If negative the photometric mode is enabled. In that case an
# explicit redshift grid must be provided in the redshfting module.
# * 'distance' (Mpc, optional): distance in Mpc. Optional, if present it
# will be used in lieu of the distance computed from the redshift
# assuming a Planck et al. (2018) cosmology.
# * band fluxes: fluxes in filters in mJy. Each column is identified
# with a unique filter name, for instance jwst.nircam.F200W for the 2 μm
# filter of the NIRCAM instrument onboard JWST. The known filters are
# avalaible from the command 'pcigale-filters list'.
# * line fluxes: fluxes in lines in W/m². Each column is identified
# after a unique line name prefixed with 'line.', for instance
# line.H-alpha. The known filters are available from the command
# 'pcigale-filters list'. It is possible to combine lines together, for
# instance line.NII-654.8+H-alpha+NII-658.3 will be the sum of Hα and
# the adjacent NII lines.
# * physical properties: values of the intensive and extensive physical
# properties (e.g., dust.luminosity for the dust luminosity). To
# determine the format of the columns and the units, it is suggested to
# do a minimal run and examine the output FITS table.
# * uncertainties: the uncertainties for the band and line fluxes as
# well as for the physical properties are given using the same column
# names with the '_err' suffix.
# Important notes:
# * Fluxes can be positive or negative.
# * Upper limits are indicated with a negative value for the
# uncertainty.
# * In case some fluxes are missing for some objects, they can be
# replaced with NaN.
# * This file is optional to generate the configuration file, in
# particular for the savefluxes module.
data_file = GSW_U.txt

# Optional file containing the list of physical parameters. Each column
# must be in the form module_name.parameter_name, with each line being a
# different model. The columns must be in the order the modules will be
# called. The redshift column must be the last one. Finally, if this
# parameter is not empty, cigale will not interpret the configuration
# parameters given in pcigale.ini. They will be given only for
# information. Note that this module should only be used in conjonction
# with the savefluxes module. Using it with the pdf_analysis module will
# yield incorrect results.
parameters_file = 

# Available modules to compute the models. The order must be kept.
# SFH:
# * sfh2exp: double exponential.
# * sfhdelayed: delayed SFH with optional exponential burst.
# * sfhdelayedbq: delayed SFH with optional constant burst/quench.
# * sfhfromfile: arbitrary SFH read from an input file.
# * sfhperiodic: periodic SFH, exponential, rectangle or delayed.
# SSP:
# * bc03: Bruzual and Charlot 2003.
# * cb19: Charlot and Bruzual 2019.
# * bpassv2: BPASS 2.2
# * m2005: Maraston 2005.
# Nebular emission:
# * nebular: continuum and line nebular emission.
# Dust attenuation:
# * dustatt_modified_CF00: modified Charlot & Fall 2000 attenuation law.
# * dustatt_modified_starburst: modified Calzetti 2000 attenuaton law.
# Dust emission:
# * casey2012: Casey 2012 dust emission models.
# * dale2014: Dale et al. 2014 dust emission templates.
# * dl2007: Draine & Li 2007 dust emission models.
# * dl2014: Draine et al. 2014 update of the previous models.
# * themis: Themis dust emission models from Jones et al. (2017).
# AGN:
# * skirtor2016: AGN models from Stalevski et al. (2012, 2016).
# * fritz2006: AGN models from Fritz et al. (2006).
# X-ray:
# * yang20 (X-ray models from Yang et al. 2020).
# * lopez24 (X-ray models from Lopez et al. 2024).
# Radio:
# * radio: galaxy synchrotron emission and AGN; note:
# skirtor2016/fritz2006 is needed for AGN.
# Restframe parameters:
# * restframe_parameters: UV slope (β), IRX, D4000, equivalent width,
# etc.
# Redshift+IGM:
# * redshifting: mandatory, also includes the IGM from Meiksin (2006).
sed_modules = sfhdelayed, bc03, nebular, dustatt_modified_starburst, dl2014, redshifting

# Method used for statistical analysis. Available methods: pdf_analysis,
# savefluxes.
analysis_method = pdf_analysis

# Number of CPU cores to use in paralel.
cores = 35

# Bands and emission lines to consider. To take uncertainties into
# account, the name of the band or line must be indicated with the _err
# suffix as in the input flux file. For instance: galex.FUV,
# galex.FUV_err. The list of allowed bands and lines can be obtained
# with pcigale-filters list. Line names must be prefixed with 'line.',
# for instance line.H-alpha, as in the input flux file.
bands = galex.FUV, galex.FUV_err, galex.NUV, galex.NUV_err, sloan.sdss.u, sloan.sdss.u_err, sloan.sdss.g, sloan.sdss.g_err, sloan.sdss.r, sloan.sdss.r_err, sloan.sdss.i, sloan.sdss.i_err, sloan.sdss.z, sloan.sdss.z_err, ukirt.wfcam.Y, ukirt.wfcam.Y_err, ukirt.wfcam.J, ukirt.wfcam.J_err, ukirt.wfcam.H, ukirt.wfcam.H_err, ukirt.wfcam.K, ukirt.wfcam.K_err, wise.W1, wise.W1_err, wise.W2, wise.W2_err, wise.W3, wise.W3_err, wise.W4, wise.W4_err

# Properties to be considered. All properties are to be given in the
# rest frame rather than the observed frame. This is the case for
# instance the equivalent widths and for luminosity densities. The names
# correspond to those used in the input file with the uncertainties
# indicated with the _err suffix.
properties = ,

# Relative error added in quadrature to the uncertainties of the fluxes
# and the extensive properties. Uncertainties on intensive properties
# are left unchanged.
additionalerror = 0.05


# Configuration of the SED creation modules.
[sed_modules_params]
  
[[sfhdelayed]]
  tau_main = 1500.0, 3000.0, 5000.0, 7000.0
  age_main = 2000, 4000, 6000
  tau_burst = 10.0, 20.0
  age_burst = 2, 4, 6, 8, 10
  f_burst = 0.005, 0.01, 0.03, 0.05
  sfr_A = 1.0
  normalise = True

[[bc03]]
  imf = 1
  metallicity = 0.004, 0.008, 0.02
  separation_age = 5, 10

[[nebular]]
  logU = -3.2, -3.0, -2.8, -2.5
  zgas = 0.004, 0.008, 0.014
  ne = 100
  f_esc = 0.0
  f_dust = 0.0
  lines_width = 500.0
  emission = True
  line_list =

[[dustatt_modified_starburst]]
  E_BV_lines = 0.0, 0.05, 0.1, 0.2, 0.3, 0.4
  E_BV_factor = 0.44, 0.6
  uv_bump_wavelength = 217.5
  uv_bump_width = 35.0
  uv_bump_amplitude = 0.0
  powerlaw_slope = -0.2, 0.0
  Ext_law_emission_lines = 1
  Rv = 3.1
  filters = galex.FUV & generic.bessell.B & generic.bessell.V

[[dl2014]]
  qpah = 0.47, 1.12
  umin = 0.5, 1.0, 2.0
  alpha = 2.0
  gamma = 0.1

[[redshifting]]
  redshift =


# Configuration of the statistical analysis method.
[analysis_params]
  # List of the physical properties to analyse. The analysis can be done
  # on the log of the value appending _log. To accelerate the computation,
  # properties of no interest to the study should be removed. Note: they
  # will still be provided for the best fit.
  variables = attenuation.E_BV_factor, attenuation.E_BV_lines, attenuation.E_BVs, attenuation.galex.FUV, attenuation.generic.bessell.B, attenuation.generic.bessell.V, attenuation.powerlaw_slope, attenuation.uv_bump_amplitude, attenuation.uv_bump_wavelength, attenuation.uv_bump_width, dust.alpha, dust.gamma, dust.luminosity, dust.mass, dust.qpah, dust.umean, dust.umin, nebular.f_dust, nebular.f_esc, nebular.lines_width, nebular.logU, nebular.ne, nebular.zgas, sfh.age, sfh.age_burst, sfh.age_main, sfh.f_burst, sfh.integrated, sfh.sfr, sfh.sfr100Myrs, sfh.sfr10Myrs, sfh.tau_burst, sfh.tau_main, stellar.age_m_star, stellar.imf, stellar.lum, stellar.lum_ly, stellar.lum_ly_old, stellar.lum_ly_young, stellar.lum_old, stellar.lum_young, stellar.m_gas, stellar.m_gas_old, stellar.m_gas_young, stellar.m_star, stellar.m_star_old, stellar.m_star_young, stellar.metallicity, stellar.n_ly, stellar.n_ly_old, stellar.n_ly_young, stellar.old_young_separation_age, universe.age, universe.luminosity_distance, universe.redshift
  # List of bands for which to estimate the fluxes. Note that this is
  # independent from the fluxes actually fitted to estimate the physical
  # properties.
  bands = galex.FUV, galex.NUV, sloan.sdss.u, sloan.sdss.g, sloan.sdss.r, sloan.sdss.i, sloan.sdss.z, ukirt.wfcam.Y, ukirt.wfcam.J, ukirt.wfcam.H, ukirt.wfcam.K, wise.W1, wise.W2, wise.W3, wise.W4
  # If true, save the best SED for each observation to a file.
  save_best_sed = True
  # Save the raw chi2. It occupies ~15 MB/million models/variable. Allowed
  # values are 'all', 'none', 'properties', and 'fluxes'.
  save_chi2 = none
  # Take into account upper limits. If 'full', the exact computation is
  # done. If 'noscaling', the scaling of the models will not be adjusted
  # but the χ² will include the upper limits adequately. Waiving the
  # adjustment makes the fitting much faster compared to the 'full' option
  # while generally not affecting the results in any substantial manner.
  # This is the recommended option as it achieves a good balance between
  # speed and reliability. Finally, 'none' simply discards bands with
  # upper limits.
  lim_flag = noscaling
  # If true, for each object we create a mock object and analyse them.
  mock_flag = False
  # When redshifts are not given explicitly in the redshifting module,
  # number of decimals to round the observed redshifts to compute the grid
  # of models. To disable rounding give a negative value. Do not round if
  # you use narrow-band filters.
  redshift_decimals = 3
  # Number of blocks to compute the models and analyse the observations.
  # If there is enough memory, we strongly recommend this to be set to 1.
  blocks = 4
